### ISSUE TITLE
Google codein task ideas

### ISSUE THREAD

**Issue by rohithasrk** [openwisp/google-code-in-sample-tasks#1]
I've started writing tasks and pointed out as many as I could. All these are very simple and basic ones. Feel free to comment

https://docs.google.com/document/d/1dlkeviUNP_oG9emuWCQKLBJI3WEWoAjia6Gphssctr4/edit?usp=sharing

**Comment by nemesisdesign** [comment]
I suggest to send a PR with at least couple of those tasks (ensure no duplicates, we have a T-Shirt task), but they need to be more specific, add details, tags and categories, example:

Title: Make a video tutorial of feature X of module Y

Text: go to the repository of module Y, click "star" and then "fork" in the upper right corner, perform a development install following instructions on <link>, play with the feature X and then make a video explaining how it works. Ensure to ask questions to your mentors to ensure you understood how feature X works before starting to record the video.

**Comment by rohithasrk** [comment]
@nemesisdesign Will work on it right now. In some time
